## PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  labels:
    app: redis
spec:
  capacity:          
    storage: 20Gi
  accessModes:       
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:               
    server: 192.168.50.101
    path: /data/rancher/gitlab/redis    
---
## PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis
  namespace: public-service
spec:
  resources:
    requests:
      storage: 20Gi      
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: redis

