---
apiVersion: v1
kind: Service
metadata:
  name: myapp2
spec:
  selector:
    app: myapp2
  ports:
  - port: 5000
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: gssjl2008/myapp
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: version
          value: v2
        ports:
        - containerPort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp2-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    nginx.ingress.kubernetes.io/canary-by-header: "cortex"
    nginx.ingress.kubernetes.io/canary-by-header-value: "all"
spec:
  rules:
  - host: myapp.cortex.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: myapp2
          servicePort: 5000
