---
apiVersion: v1
kind: Service
metadata:
  name: myapp1
spec:
  selector:
    app: myapp1
  ports:
  - port: 5000
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: gssjl2008/myapp
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: version
          value: v1
        ports:
        - containerPort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp1-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: myapp.cortex.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: myapp1
          servicePort: 5000
