apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: public-service
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        lifecycle:
          postStart:
            exec:
              command: [ '/bin/sh', '-c', 'redis-cli config set requirepass password' ]
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /var/lib/redis
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: public-service
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: public-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
